// This file is auto-generated by @hey-api/openapi-ts

export type AdministrativeRegionPublic = {
    id: number;
    name: string;
    name_en: string;
    code_name?: (string | null);
    code_name_en?: (string | null);
};

export type AdministrativeUnitPublic = {
    id: number;
    full_name?: (string | null);
    full_name_en?: (string | null);
    short_name?: (string | null);
    short_name_en?: (string | null);
    code_name?: (string | null);
    code_name_en?: (string | null);
};

export type AIRaceSuggestion = {
    description?: (string | null);
    location?: (string | null);
    terrain_type?: (string | null);
    difficulty_level?: (string | null);
    elevation_gain_m?: (string | null);
};

export type AskRequest = {
    question: string;
};

export type AttributeTypeEnum = 'string' | 'text' | 'url' | 'date' | 'datetime' | 'number' | 'boolean' | 'email' | 'phone';

export type BlogCategoriesPublic = {
    data: Array<BlogCategoryPublic>;
    count: number;
};

export type BlogCategoryCreate = {
    name: string;
    slug: string;
    description?: (string | null);
    parent_id?: (string | null);
    is_active?: boolean;
    display_order?: number;
    meta_title?: (string | null);
    meta_description?: (string | null);
    translations?: ({
    [key: string]: unknown;
} | null);
};

export type BlogCategoryPublic = {
    name: string;
    slug: string;
    description?: (string | null);
    parent_id?: (string | null);
    is_active?: boolean;
    display_order?: number;
    meta_title?: (string | null);
    meta_description?: (string | null);
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Update translations for a blog category
 */
export type BlogCategoryTranslationUpdate = {
    language: string;
    name?: (string | null);
    description?: (string | null);
};

export type BlogCategoryUpdate = {
    name?: (string | null);
    slug?: (string | null);
    description?: (string | null);
    parent_id?: (string | null);
    is_active?: (boolean | null);
    display_order?: (number | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
};

export type BlogPostCreate = {
    title: string;
    slug: string;
    content?: (string | null);
    excerpt?: (string | null);
    featured_image_url?: (string | null);
    featured_image_alt?: (string | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
    meta_keywords?: (string | null);
    og_title?: (string | null);
    og_description?: (string | null);
    og_image_url?: (string | null);
    canonical_url?: (string | null);
    status?: BlogPostStatusEnum;
    published_at?: (string | null);
    scheduled_at?: (string | null);
    is_featured?: boolean;
    is_sticky?: boolean;
    view_count?: number;
    like_count?: number;
    comment_count?: number;
    reading_time_minutes?: (number | null);
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    post_metadata?: ({
    [key: string]: unknown;
} | null);
    category_id?: (string | null);
    tag_ids?: (Array<(string)> | null);
};

export type BlogPostPublic = {
    title: string;
    slug: string;
    content?: (string | null);
    excerpt?: (string | null);
    featured_image_url?: (string | null);
    featured_image_alt?: (string | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
    meta_keywords?: (string | null);
    og_title?: (string | null);
    og_description?: (string | null);
    og_image_url?: (string | null);
    canonical_url?: (string | null);
    status?: BlogPostStatusEnum;
    published_at?: (string | null);
    scheduled_at?: (string | null);
    is_featured?: boolean;
    is_sticky?: boolean;
    view_count?: number;
    like_count?: number;
    comment_count?: number;
    reading_time_minutes?: (number | null);
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    post_metadata?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
    category_id?: (string | null);
    author_id: string;
};

export type BlogPostsPublic = {
    data: Array<BlogPostPublic>;
    count: number;
};

export type BlogPostStatusEnum = 'draft' | 'published' | 'scheduled' | 'archived';

/**
 * Update translations for a blog post
 */
export type BlogPostTranslationUpdate = {
    language: string;
    title?: (string | null);
    content?: (string | null);
    excerpt?: (string | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
};

export type BlogPostUpdate = {
    title?: (string | null);
    slug?: (string | null);
    content?: (string | null);
    excerpt?: (string | null);
    featured_image_url?: (string | null);
    featured_image_alt?: (string | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
    meta_keywords?: (string | null);
    og_title?: (string | null);
    og_description?: (string | null);
    og_image_url?: (string | null);
    canonical_url?: (string | null);
    status?: (BlogPostStatusEnum | null);
    published_at?: (string | null);
    scheduled_at?: (string | null);
    is_featured?: (boolean | null);
    is_sticky?: (boolean | null);
    reading_time_minutes?: (number | null);
    category_id?: (string | null);
    tag_ids?: (Array<(string)> | null);
    post_metadata?: ({
    [key: string]: unknown;
} | null);
};

export type BlogTagCreate = {
    name: string;
    slug: string;
    is_active?: boolean;
    translations?: ({
    [key: string]: unknown;
} | null);
};

export type BlogTagPublic = {
    name: string;
    slug: string;
    is_active?: boolean;
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
};

export type BlogTagsPublic = {
    data: Array<BlogTagPublic>;
    count: number;
};

/**
 * Update translations for a blog tag
 */
export type BlogTagTranslationUpdate = {
    language: string;
    name?: (string | null);
};

export type BlogTagUpdate = {
    name?: (string | null);
    slug?: (string | null);
    is_active?: (boolean | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_media_upload_media_asset = {
    file: string;
    content_type: string;
    content_id: string;
    kind?: string;
    alt_text?: (string | null);
    display_order?: number;
    is_primary?: boolean;
    is_public?: boolean;
};

/**
 * Update translations for a race category
 */
export type CategoryTranslationUpdate = {
    language: string;
    name?: (string | null);
    description?: (string | null);
};

export type DescriptionSuggestion = {
    description: string;
};

export type DifficultyEnum = 'easy' | 'moderate' | 'hard' | 'extreme';

export type DistancePrefEnum = 'short' | 'mid' | 'long' | 'ultra';

export type FitnessEnum = 'beginner' | 'intermediate' | 'advanced' | 'elite';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImageGenerationInput = {
    race_name: string;
    location?: (string | null);
    image_type?: string;
};

export type InteractionTypeEnum = 'viewed' | 'saved' | 'unsaved' | 'registered' | 'shared';

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MediaAssetPublic = {
    content_type: string;
    content_id: string;
    kind?: string;
    alt_text?: (string | null);
    display_order?: number;
    is_primary?: boolean;
    is_public?: boolean;
    id: string;
    original_filename: string;
    file_name: string;
    file_url: string;
    mime_type: string;
    size_bytes: number;
    uploaded_by_id?: (string | null);
    created_at: string;
    updated_at: string;
};

export type MediaAssetsPublic = {
    data: Array<MediaAssetPublic>;
    count: number;
};

export type MediaAssetUpdate = {
    kind?: (string | null);
    alt_text?: (string | null);
    display_order?: (number | null);
    is_primary?: (boolean | null);
    is_public?: (boolean | null);
};

export type MediaFolderCreate = {
    name: string;
    description?: (string | null);
    parent_id?: (string | null);
    is_active?: boolean;
};

export type MediaFolderPublic = {
    name: string;
    description?: (string | null);
    parent_id?: (string | null);
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
    created_by_id: string;
};

export type MediaFoldersPublic = {
    data: Array<MediaFolderPublic>;
    count: number;
};

export type MediaFolderUpdate = {
    name?: (string | null);
    description?: (string | null);
    parent_id?: (string | null);
    is_active?: (boolean | null);
};

export type MenuCreate = {
    name: string;
    slug: string;
    description?: (string | null);
    location?: string;
    is_active?: boolean;
};

export type MenuItemCreate = {
    label: string;
    url: string;
    title?: (string | null);
    target?: string;
    icon?: (string | null);
    parent_id?: (string | null);
    display_order?: number;
    is_active?: boolean;
    css_classes?: (string | null);
    translations?: ({
    [key: string]: unknown;
} | null);
    menu_id: string;
};

export type MenuItemPublic = {
    label: string;
    url: string;
    title?: (string | null);
    target?: string;
    icon?: (string | null);
    parent_id?: (string | null);
    display_order?: number;
    is_active?: boolean;
    css_classes?: (string | null);
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    menu_id: string;
    created_at: string;
    updated_at: string;
};

export type MenuItemsPublic = {
    data: Array<MenuItemPublic>;
    count: number;
};

/**
 * Update translations for a menu item
 */
export type MenuItemTranslationUpdate = {
    language: string;
    label?: (string | null);
};

export type MenuItemUpdate = {
    label?: (string | null);
    url?: (string | null);
    title?: (string | null);
    target?: (string | null);
    icon?: (string | null);
    parent_id?: (string | null);
    display_order?: (number | null);
    is_active?: (boolean | null);
    css_classes?: (string | null);
};

export type MenuPublic = {
    name: string;
    slug: string;
    description?: (string | null);
    location?: string;
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type MenusPublic = {
    data: Array<MenuPublic>;
    count: number;
};

export type MenuUpdate = {
    name?: (string | null);
    slug?: (string | null);
    description?: (string | null);
    location?: (string | null);
    is_active?: (boolean | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PageCreate = {
    title: string;
    slug: string;
    content?: (string | null);
    excerpt?: (string | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
    meta_keywords?: (string | null);
    og_title?: (string | null);
    og_description?: (string | null);
    og_image_url?: (string | null);
    canonical_url?: (string | null);
    status?: PageStatusEnum;
    published_at?: (string | null);
    scheduled_at?: (string | null);
    template?: string;
    is_homepage?: boolean;
    is_visible_in_menu?: boolean;
    display_order?: number;
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    page_metadata?: ({
    [key: string]: unknown;
} | null);
};

export type PagePublic = {
    title: string;
    slug: string;
    content?: (string | null);
    excerpt?: (string | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
    meta_keywords?: (string | null);
    og_title?: (string | null);
    og_description?: (string | null);
    og_image_url?: (string | null);
    canonical_url?: (string | null);
    status?: PageStatusEnum;
    published_at?: (string | null);
    scheduled_at?: (string | null);
    template?: string;
    is_homepage?: boolean;
    is_visible_in_menu?: boolean;
    display_order?: number;
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    page_metadata?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
    created_by_id: string;
    updated_by_id?: (string | null);
};

export type PagesPublic = {
    data: Array<PagePublic>;
    count: number;
};

export type PageStatusEnum = 'draft' | 'published' | 'scheduled' | 'archived';

/**
 * Update translations for a page
 */
export type PageTranslationUpdate = {
    language: string;
    title?: (string | null);
    content?: (string | null);
    excerpt?: (string | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
};

export type PageUpdate = {
    title?: (string | null);
    slug?: (string | null);
    content?: (string | null);
    excerpt?: (string | null);
    meta_title?: (string | null);
    meta_description?: (string | null);
    meta_keywords?: (string | null);
    og_title?: (string | null);
    og_description?: (string | null);
    og_image_url?: (string | null);
    canonical_url?: (string | null);
    status?: (PageStatusEnum | null);
    published_at?: (string | null);
    scheduled_at?: (string | null);
    template?: (string | null);
    is_homepage?: (boolean | null);
    is_visible_in_menu?: (boolean | null);
    display_order?: (number | null);
    page_metadata?: ({
    [key: string]: unknown;
} | null);
};

export type PaymentStatusEnum = 'unpaid' | 'paid' | 'refunded' | 'partial';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProvincePublic = {
    code: string;
    name: string;
    name_en?: (string | null);
    full_name: string;
    full_name_en?: (string | null);
    code_name?: (string | null);
    administrative_unit_id?: (number | null);
};

export type ProvincePublicWithDetails = {
    code: string;
    name: string;
    name_en?: (string | null);
    full_name: string;
    full_name_en?: (string | null);
    code_name?: (string | null);
    administrative_unit_id?: (number | null);
    administrative_unit?: (AdministrativeUnitPublic | null);
};

export type ProvincesPublic = {
    data: Array<ProvincePublic>;
    count: number;
};

export type RaceAnswer = {
    answer: string;
};

export type RaceAttributeCreate = {
    key: string;
    value_text?: (string | null);
    attribute_type?: AttributeTypeEnum;
    label?: (string | null);
    description?: (string | null);
    is_required?: boolean;
    is_public?: boolean;
    display_order?: number;
    race_id: string;
};

export type RaceAttributePublic = {
    key: string;
    value_text?: (string | null);
    attribute_type?: AttributeTypeEnum;
    label?: (string | null);
    description?: (string | null);
    is_required?: boolean;
    is_public?: boolean;
    display_order?: number;
    id: string;
    race_id: string;
    created_at: string;
    updated_at: string;
};

export type RaceAttributesPublic = {
    data: Array<RaceAttributePublic>;
    count: number;
};

export type RaceAttributeUpdate = {
    value_text?: (string | null);
    attribute_type?: (AttributeTypeEnum | null);
    label?: (string | null);
    description?: (string | null);
    is_required?: (boolean | null);
    is_public?: (boolean | null);
    display_order?: (number | null);
};

export type RaceCategoriesPublic = {
    data: Array<RaceCategoryPublic>;
    count: number;
};

export type RaceCategoryCreate = {
    name: string;
    distance_km: number;
    distance_unit?: string;
    start_time?: (string | null);
    end_time?: (string | null);
    cutoff_time_minutes?: (number | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    price?: (number | null);
    early_bird_price?: (number | null);
    early_bird_deadline?: (string | null);
    max_participants?: (number | null);
    min_age?: (number | null);
    max_age?: (number | null);
    gender_restriction?: (string | null);
    description?: (string | null);
    display_order?: number;
    is_active?: boolean;
    translations?: ({
    [key: string]: unknown;
} | null);
    race_id: string;
};

export type RaceCategoryPublic = {
    name: string;
    distance_km: number;
    distance_unit?: string;
    start_time?: (string | null);
    end_time?: (string | null);
    cutoff_time_minutes?: (number | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    price?: (number | null);
    early_bird_price?: (number | null);
    early_bird_deadline?: (string | null);
    max_participants?: (number | null);
    min_age?: (number | null);
    max_age?: (number | null);
    gender_restriction?: (string | null);
    description?: (string | null);
    display_order?: number;
    is_active?: boolean;
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    race_id: string;
    created_at: string;
    updated_at: string;
};

export type RaceCategoryPublicWithDetails = {
    name: string;
    distance_km: number;
    distance_unit?: string;
    start_time?: (string | null);
    end_time?: (string | null);
    cutoff_time_minutes?: (number | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    price?: (number | null);
    early_bird_price?: (number | null);
    early_bird_deadline?: (string | null);
    max_participants?: (number | null);
    min_age?: (number | null);
    max_age?: (number | null);
    gender_restriction?: (string | null);
    description?: (string | null);
    display_order?: number;
    is_active?: boolean;
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    race_id: string;
    created_at: string;
    updated_at: string;
    registration_count?: number;
    available_spots?: (number | null);
    is_registration_open?: boolean;
    current_price?: (number | null);
};

export type RaceCategoryUpdate = {
    name?: (string | null);
    distance_km?: (number | null);
    distance_unit?: (string | null);
    start_time?: (string | null);
    end_time?: (string | null);
    cutoff_time_minutes?: (number | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    price?: (number | null);
    early_bird_price?: (number | null);
    early_bird_deadline?: (string | null);
    max_participants?: (number | null);
    min_age?: (number | null);
    max_age?: (number | null);
    gender_restriction?: (string | null);
    description?: (string | null);
    display_order?: (number | null);
    is_active?: (boolean | null);
};

export type RaceCreate = {
    name: string;
    description?: (string | null);
    event_start_date: string;
    event_end_date?: (string | null);
    location: string;
    city?: (string | null);
    state?: (string | null);
    country?: string;
    province_code?: (string | null);
    ward_code?: (string | null);
    country_code?: (string | null);
    province_name?: (string | null);
    ward_name?: (string | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    status?: RaceStatusEnum;
    is_active?: boolean;
    base_price?: (number | null);
    currency?: string;
    race_metadata?: ({
    [key: string]: unknown;
} | null);
    latitude?: (number | null);
    longitude?: (number | null);
    terrain_type?: (TerrainEnum | null);
    difficulty_level?: (DifficultyEnum | null);
    elevation_gain_m?: (number | null);
    is_certified?: boolean;
    gpx_file_url?: (string | null);
    website_url?: (string | null);
    cover_image_url?: (string | null);
    banner_image_url?: (string | null);
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
};

export type RaceNameInput = {
    name: string;
};

export type RacePublic = {
    name: string;
    description?: (string | null);
    event_start_date: string;
    event_end_date?: (string | null);
    location: string;
    city?: (string | null);
    state?: (string | null);
    country?: string;
    province_code?: (string | null);
    ward_code?: (string | null);
    country_code?: (string | null);
    province_name?: (string | null);
    ward_name?: (string | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    status?: RaceStatusEnum;
    is_active?: boolean;
    base_price?: (number | null);
    currency?: string;
    race_metadata?: ({
    [key: string]: unknown;
} | null);
    latitude?: (number | null);
    longitude?: (number | null);
    terrain_type?: (TerrainEnum | null);
    difficulty_level?: (DifficultyEnum | null);
    elevation_gain_m?: (number | null);
    is_certified?: boolean;
    gpx_file_url?: (string | null);
    website_url?: (string | null);
    cover_image_url?: (string | null);
    banner_image_url?: (string | null);
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
    organizer_id: string;
};

export type RacePublicWithDetails = {
    name: string;
    description?: (string | null);
    event_start_date: string;
    event_end_date?: (string | null);
    location: string;
    city?: (string | null);
    state?: (string | null);
    country?: string;
    province_code?: (string | null);
    ward_code?: (string | null);
    country_code?: (string | null);
    province_name?: (string | null);
    ward_name?: (string | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    status?: RaceStatusEnum;
    is_active?: boolean;
    base_price?: (number | null);
    currency?: string;
    race_metadata?: ({
    [key: string]: unknown;
} | null);
    latitude?: (number | null);
    longitude?: (number | null);
    terrain_type?: (TerrainEnum | null);
    difficulty_level?: (DifficultyEnum | null);
    elevation_gain_m?: (number | null);
    is_certified?: boolean;
    gpx_file_url?: (string | null);
    website_url?: (string | null);
    cover_image_url?: (string | null);
    banner_image_url?: (string | null);
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
    organizer_id: string;
    categories?: Array<RaceCategoryPublic>;
    tags?: Array<TagPublic>;
    registration_count?: number;
    province?: (ProvincePublic | null);
    ward?: (WardPublic | null);
};

export type RacePublicWithDistance = {
    name: string;
    description?: (string | null);
    event_start_date: string;
    event_end_date?: (string | null);
    location: string;
    city?: (string | null);
    state?: (string | null);
    country?: string;
    province_code?: (string | null);
    ward_code?: (string | null);
    country_code?: (string | null);
    province_name?: (string | null);
    ward_name?: (string | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    status?: RaceStatusEnum;
    is_active?: boolean;
    base_price?: (number | null);
    currency?: string;
    race_metadata?: ({
    [key: string]: unknown;
} | null);
    latitude?: (number | null);
    longitude?: (number | null);
    terrain_type?: (TerrainEnum | null);
    difficulty_level?: (DifficultyEnum | null);
    elevation_gain_m?: (number | null);
    is_certified?: boolean;
    gpx_file_url?: (string | null);
    website_url?: (string | null);
    cover_image_url?: (string | null);
    banner_image_url?: (string | null);
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
    organizer_id: string;
    distance_km: number;
};

export type RacePublicWithExplanation = {
    name: string;
    description?: (string | null);
    event_start_date: string;
    event_end_date?: (string | null);
    location: string;
    city?: (string | null);
    state?: (string | null);
    country?: string;
    province_code?: (string | null);
    ward_code?: (string | null);
    country_code?: (string | null);
    province_name?: (string | null);
    ward_name?: (string | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    status?: RaceStatusEnum;
    is_active?: boolean;
    base_price?: (number | null);
    currency?: string;
    race_metadata?: ({
    [key: string]: unknown;
} | null);
    latitude?: (number | null);
    longitude?: (number | null);
    terrain_type?: (TerrainEnum | null);
    difficulty_level?: (DifficultyEnum | null);
    elevation_gain_m?: (number | null);
    is_certified?: boolean;
    gpx_file_url?: (string | null);
    website_url?: (string | null);
    cover_image_url?: (string | null);
    banner_image_url?: (string | null);
    default_language?: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
    updated_at: string;
    organizer_id: string;
    ai_explanation?: (string | null);
};

export type RaceRegistrationCreate = {
    bib_number?: (string | null);
    emergency_contact?: (string | null);
    emergency_phone?: (string | null);
    tshirt_size?: (string | null);
    special_requirements?: (string | null);
    registration_status?: RegistrationStatusEnum;
    payment_status?: PaymentStatusEnum;
    amount_paid?: (number | null);
    payment_reference?: (string | null);
    registration_data?: ({
    [key: string]: unknown;
} | null);
    race_id: string;
    category_id: string;
};

export type RaceRegistrationPublic = {
    bib_number?: (string | null);
    emergency_contact?: (string | null);
    emergency_phone?: (string | null);
    tshirt_size?: (string | null);
    special_requirements?: (string | null);
    registration_status?: RegistrationStatusEnum;
    payment_status?: PaymentStatusEnum;
    amount_paid?: (number | null);
    payment_reference?: (string | null);
    registration_data?: ({
    [key: string]: unknown;
} | null);
    id: string;
    race_id: string;
    category_id: string;
    runner_id: string;
    registered_at: string;
    updated_at: string;
};

export type RaceRegistrationPublicWithDetails = {
    bib_number?: (string | null);
    emergency_contact?: (string | null);
    emergency_phone?: (string | null);
    tshirt_size?: (string | null);
    special_requirements?: (string | null);
    registration_status?: RegistrationStatusEnum;
    payment_status?: PaymentStatusEnum;
    amount_paid?: (number | null);
    payment_reference?: (string | null);
    registration_data?: ({
    [key: string]: unknown;
} | null);
    id: string;
    race_id: string;
    category_id: string;
    runner_id: string;
    registered_at: string;
    updated_at: string;
    runner: UserPublic;
    category: RaceCategoryPublic;
};

export type RaceRegistrationsPublic = {
    data: Array<RaceRegistrationPublic>;
    count: number;
};

export type RaceRegistrationUpdate = {
    bib_number?: (string | null);
    emergency_contact?: (string | null);
    emergency_phone?: (string | null);
    tshirt_size?: (string | null);
    special_requirements?: (string | null);
    registration_status?: (RegistrationStatusEnum | null);
    payment_status?: (PaymentStatusEnum | null);
    amount_paid?: (number | null);
    payment_reference?: (string | null);
    registration_data?: ({
    [key: string]: unknown;
} | null);
};

export type RaceResultCreate = {
    finish_time_seconds?: (number | null);
    overall_position?: (number | null);
    category_position?: (number | null);
    gender_position?: (number | null);
    status?: ResultStatusEnum;
    pace_per_km_seconds?: (number | null);
    notes?: (string | null);
    registration_id: string;
};

export type RaceResultPublic = {
    finish_time_seconds?: (number | null);
    overall_position?: (number | null);
    category_position?: (number | null);
    gender_position?: (number | null);
    status?: ResultStatusEnum;
    pace_per_km_seconds?: (number | null);
    notes?: (string | null);
    id: string;
    registration_id: string;
    created_at: string;
    updated_at: string;
};

export type RaceResultsPublic = {
    data: Array<RaceResultPublic>;
    count: number;
};

export type RaceResultUpdate = {
    finish_time_seconds?: (number | null);
    overall_position?: (number | null);
    category_position?: (number | null);
    gender_position?: (number | null);
    status?: (ResultStatusEnum | null);
    pace_per_km_seconds?: (number | null);
    notes?: (string | null);
};

export type RacesPublic = {
    data: Array<RacePublic>;
    count: number;
};

export type RacesPublicWithDistance = {
    data: Array<RacePublicWithDistance>;
    count: number;
};

export type RacesPublicWithExplanation = {
    data: Array<RacePublicWithExplanation>;
    count: number;
};

export type RaceStatusEnum = 'draft' | 'published' | 'registration_open' | 'registration_closed' | 'completed' | 'cancelled';

export type RaceTagCreate = {
    name: string;
    slug: string;
    translations?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Update translations for a race
 */
export type RaceTranslationUpdate = {
    language: string;
    name?: (string | null);
    description?: (string | null);
    location?: (string | null);
};

export type RaceUpdate = {
    name?: (string | null);
    description?: (string | null);
    event_start_date?: (string | null);
    event_end_date?: (string | null);
    location?: (string | null);
    city?: (string | null);
    state?: (string | null);
    country?: (string | null);
    province_code?: (string | null);
    ward_code?: (string | null);
    country_code?: (string | null);
    province_name?: (string | null);
    ward_name?: (string | null);
    registration_start?: (string | null);
    registration_end?: (string | null);
    status?: (RaceStatusEnum | null);
    is_active?: (boolean | null);
    base_price?: (number | null);
    currency?: (string | null);
    race_metadata?: ({
    [key: string]: unknown;
} | null);
    latitude?: (number | null);
    longitude?: (number | null);
    terrain_type?: (TerrainEnum | null);
    difficulty_level?: (DifficultyEnum | null);
    elevation_gain_m?: (number | null);
    is_certified?: (boolean | null);
    gpx_file_url?: (string | null);
    website_url?: (string | null);
    cover_image_url?: (string | null);
    banner_image_url?: (string | null);
    tag_ids?: (Array<(string)> | null);
};

export type RegistrationStatusEnum = 'pending' | 'confirmed' | 'cancelled' | 'waitlist';

export type ResultStatusEnum = 'finished' | 'dnf' | 'dns' | 'dq';

export type RoleCreate = {
    name: string;
    description?: (string | null);
};

export type RolePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type RoleUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type TagPublic = {
    name: string;
    slug: string;
    translations?: ({
    [key: string]: unknown;
} | null);
    id: string;
};

export type TagsPublic = {
    data: Array<TagPublic>;
    count: number;
};

export type TagSuggestion = {
    tags: Array<(string)>;
};

/**
 * Update translations for a tag
 */
export type TagTranslationUpdate = {
    language: string;
    name?: (string | null);
};

export type TerrainEnum = 'road' | 'trail' | 'track' | 'mixed';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserProfileCreate = {
    fitness_level?: (FitnessEnum | null);
    distance_preference?: (DistancePrefEnum | null);
    terrain_preference?: (TerrainEnum | null);
    home_latitude?: (number | null);
    home_longitude?: (number | null);
    home_city?: (string | null);
    weekly_mileage_km?: (number | null);
    goal_race_date?: (string | null);
    bio?: (string | null);
    is_onboarded?: boolean;
};

export type UserProfilePublic = {
    fitness_level?: (FitnessEnum | null);
    distance_preference?: (DistancePrefEnum | null);
    terrain_preference?: (TerrainEnum | null);
    home_latitude?: (number | null);
    home_longitude?: (number | null);
    home_city?: (string | null);
    weekly_mileage_km?: (number | null);
    goal_race_date?: (string | null);
    bio?: (string | null);
    is_onboarded?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type UserProfileUpdate = {
    fitness_level?: (FitnessEnum | null);
    distance_preference?: (DistancePrefEnum | null);
    terrain_preference?: (TerrainEnum | null);
    home_latitude?: (number | null);
    home_longitude?: (number | null);
    home_city?: (string | null);
    weekly_mileage_km?: (number | null);
    goal_race_date?: (string | null);
    bio?: (string | null);
    is_onboarded?: (boolean | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    roles?: Array<RolePublic>;
};

export type UserRaceInteractionPublic = {
    id: string;
    user_id: string;
    race_id: string;
    action: InteractionTypeEnum;
    created_at: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WardPublic = {
    code: string;
    name: string;
    name_en?: (string | null);
    full_name?: (string | null);
    full_name_en?: (string | null);
    code_name?: (string | null);
    province_code?: (string | null);
    administrative_unit_id?: (number | null);
};

export type WardPublicWithDetails = {
    code: string;
    name: string;
    name_en?: (string | null);
    full_name?: (string | null);
    full_name_en?: (string | null);
    code_name?: (string | null);
    province_code?: (string | null);
    administrative_unit_id?: (number | null);
    administrative_unit?: (AdministrativeUnitPublic | null);
};

export type WardsPublic = {
    data: Array<WardPublic>;
    count: number;
};

export type AdminReindexRaceEmbeddingsData = {
    batchSize?: number;
};

export type AdminReindexRaceEmbeddingsResponse = (Message);

export type CmsBlogCategoriesReadBlogCategoriesData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type CmsBlogCategoriesReadBlogCategoriesResponse = (BlogCategoriesPublic);

export type CmsBlogCategoriesCreateBlogCategoryData = {
    requestBody: BlogCategoryCreate;
};

export type CmsBlogCategoriesCreateBlogCategoryResponse = (BlogCategoryPublic);

export type CmsBlogCategoriesReadBlogCategoryData = {
    categoryId: string;
};

export type CmsBlogCategoriesReadBlogCategoryResponse = (BlogCategoryPublic);

export type CmsBlogCategoriesUpdateBlogCategoryData = {
    categoryId: string;
    requestBody: BlogCategoryUpdate;
};

export type CmsBlogCategoriesUpdateBlogCategoryResponse = (BlogCategoryPublic);

export type CmsBlogCategoriesDeleteBlogCategoryData = {
    categoryId: string;
};

export type CmsBlogCategoriesDeleteBlogCategoryResponse = (Message);

export type CmsBlogCategoriesReadBlogCategoryBySlugData = {
    slug: string;
};

export type CmsBlogCategoriesReadBlogCategoryBySlugResponse = (BlogCategoryPublic);

export type CmsBlogCategoriesUpdateBlogCategoryTranslationData = {
    categoryId: string;
    requestBody: BlogCategoryTranslationUpdate;
};

export type CmsBlogCategoriesUpdateBlogCategoryTranslationResponse = (BlogCategoryPublic);

export type CmsBlogPostsReadBlogPostsData = {
    /**
     * Filter by author
     */
    authorId?: (string | null);
    /**
     * Filter by category
     */
    categoryId?: (string | null);
    /**
     * Filter by featured
     */
    isFeatured?: (boolean | null);
    limit?: number;
    skip?: number;
    /**
     * Filter by status
     */
    status?: (string | null);
    /**
     * Filter by tag
     */
    tagId?: (string | null);
};

export type CmsBlogPostsReadBlogPostsResponse = (BlogPostsPublic);

export type CmsBlogPostsCreateBlogPostData = {
    requestBody: BlogPostCreate;
};

export type CmsBlogPostsCreateBlogPostResponse = (BlogPostPublic);

export type CmsBlogPostsReadBlogPostData = {
    postId: string;
};

export type CmsBlogPostsReadBlogPostResponse = (BlogPostPublic);

export type CmsBlogPostsUpdateBlogPostData = {
    postId: string;
    requestBody: BlogPostUpdate;
};

export type CmsBlogPostsUpdateBlogPostResponse = (BlogPostPublic);

export type CmsBlogPostsDeleteBlogPostData = {
    postId: string;
};

export type CmsBlogPostsDeleteBlogPostResponse = (Message);

export type CmsBlogPostsReadBlogPostBySlugData = {
    slug: string;
};

export type CmsBlogPostsReadBlogPostBySlugResponse = (BlogPostPublic);

export type CmsBlogPostsUpdateBlogPostTranslationData = {
    postId: string;
    requestBody: BlogPostTranslationUpdate;
};

export type CmsBlogPostsUpdateBlogPostTranslationResponse = (BlogPostPublic);

export type CmsBlogTagsReadBlogTagsData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type CmsBlogTagsReadBlogTagsResponse = (BlogTagsPublic);

export type CmsBlogTagsCreateBlogTagData = {
    requestBody: BlogTagCreate;
};

export type CmsBlogTagsCreateBlogTagResponse = (BlogTagPublic);

export type CmsBlogTagsReadBlogTagData = {
    tagId: string;
};

export type CmsBlogTagsReadBlogTagResponse = (BlogTagPublic);

export type CmsBlogTagsUpdateBlogTagData = {
    requestBody: BlogTagUpdate;
    tagId: string;
};

export type CmsBlogTagsUpdateBlogTagResponse = (BlogTagPublic);

export type CmsBlogTagsDeleteBlogTagData = {
    tagId: string;
};

export type CmsBlogTagsDeleteBlogTagResponse = (Message);

export type CmsBlogTagsReadBlogTagBySlugData = {
    slug: string;
};

export type CmsBlogTagsReadBlogTagBySlugResponse = (BlogTagPublic);

export type CmsBlogTagsUpdateBlogTagTranslationData = {
    requestBody: BlogTagTranslationUpdate;
    tagId: string;
};

export type CmsBlogTagsUpdateBlogTagTranslationResponse = (BlogTagPublic);

export type CmsMediaFoldersReadMediaFoldersData = {
    limit?: number;
    /**
     * Filter by parent folder
     */
    parentId?: (string | null);
    skip?: number;
};

export type CmsMediaFoldersReadMediaFoldersResponse = (MediaFoldersPublic);

export type CmsMediaFoldersCreateMediaFolderData = {
    requestBody: MediaFolderCreate;
};

export type CmsMediaFoldersCreateMediaFolderResponse = (MediaFolderPublic);

export type CmsMediaFoldersReadMediaFolderData = {
    folderId: string;
};

export type CmsMediaFoldersReadMediaFolderResponse = (MediaFolderPublic);

export type CmsMediaFoldersUpdateMediaFolderData = {
    folderId: string;
    requestBody: MediaFolderUpdate;
};

export type CmsMediaFoldersUpdateMediaFolderResponse = (MediaFolderPublic);

export type CmsMediaFoldersDeleteMediaFolderData = {
    folderId: string;
};

export type CmsMediaFoldersDeleteMediaFolderResponse = (Message);

export type CmsMenusReadMenusData = {
    limit?: number;
    /**
     * Filter by location
     */
    location?: (string | null);
    skip?: number;
};

export type CmsMenusReadMenusResponse = (MenusPublic);

export type CmsMenusCreateMenuData = {
    requestBody: MenuCreate;
};

export type CmsMenusCreateMenuResponse = (MenuPublic);

export type CmsMenusReadMenuData = {
    menuId: string;
};

export type CmsMenusReadMenuResponse = (MenuPublic);

export type CmsMenusUpdateMenuData = {
    menuId: string;
    requestBody: MenuUpdate;
};

export type CmsMenusUpdateMenuResponse = (MenuPublic);

export type CmsMenusDeleteMenuData = {
    menuId: string;
};

export type CmsMenusDeleteMenuResponse = (Message);

export type CmsMenusReadMenuBySlugData = {
    slug: string;
};

export type CmsMenusReadMenuBySlugResponse = (MenuPublic);

export type CmsMenusReadMenuItemsData = {
    menuId: string;
    /**
     * Filter by parent
     */
    parentId?: (string | null);
};

export type CmsMenusReadMenuItemsResponse = (MenuItemsPublic);

export type CmsMenusCreateMenuItemData = {
    menuId: string;
    requestBody: MenuItemCreate;
};

export type CmsMenusCreateMenuItemResponse = (MenuItemPublic);

export type CmsMenusReadMenuItemData = {
    itemId: string;
};

export type CmsMenusReadMenuItemResponse = (MenuItemPublic);

export type CmsMenusUpdateMenuItemData = {
    itemId: string;
    requestBody: MenuItemUpdate;
};

export type CmsMenusUpdateMenuItemResponse = (MenuItemPublic);

export type CmsMenusDeleteMenuItemData = {
    itemId: string;
};

export type CmsMenusDeleteMenuItemResponse = (Message);

export type CmsMenusUpdateMenuItemTranslationData = {
    itemId: string;
    requestBody: MenuItemTranslationUpdate;
};

export type CmsMenusUpdateMenuItemTranslationResponse = (MenuItemPublic);

export type CmsPagesReadPagesData = {
    /**
     * Filter by homepage
     */
    isHomepage?: (boolean | null);
    limit?: number;
    skip?: number;
    /**
     * Filter by status
     */
    status?: (string | null);
};

export type CmsPagesReadPagesResponse = (PagesPublic);

export type CmsPagesCreatePageData = {
    requestBody: PageCreate;
};

export type CmsPagesCreatePageResponse = (PagePublic);

export type CmsPagesReadPageData = {
    pageId: string;
};

export type CmsPagesReadPageResponse = (PagePublic);

export type CmsPagesUpdatePageData = {
    pageId: string;
    requestBody: PageUpdate;
};

export type CmsPagesUpdatePageResponse = (PagePublic);

export type CmsPagesDeletePageData = {
    pageId: string;
};

export type CmsPagesDeletePageResponse = (Message);

export type CmsPagesReadPageBySlugData = {
    slug: string;
};

export type CmsPagesReadPageBySlugResponse = (PagePublic);

export type CmsPagesUpdatePageTranslationData = {
    pageId: string;
    requestBody: PageTranslationUpdate;
};

export type CmsPagesUpdatePageTranslationResponse = (PagePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaReadMediaAssetsData = {
    contentId?: (string | null);
    contentType?: (string | null);
    isPublic?: boolean;
    kind?: (string | null);
    limit?: number;
    skip?: number;
};

export type MediaReadMediaAssetsResponse = (MediaAssetsPublic);

export type MediaUploadMediaAssetData = {
    formData: Body_media_upload_media_asset;
};

export type MediaUploadMediaAssetResponse = (MediaAssetPublic);

export type MediaReadMediaFileData = {
    mediaId: string;
};

export type MediaReadMediaFileResponse = (unknown);

export type MediaUpdateMediaAssetData = {
    mediaId: string;
    requestBody: MediaAssetUpdate;
};

export type MediaUpdateMediaAssetResponse = (MediaAssetPublic);

export type MediaDeleteMediaAssetData = {
    mediaId: string;
};

export type MediaDeleteMediaAssetResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfilesGetMyProfileResponse = (UserProfilePublic);

export type ProfilesUpsertMyProfileData = {
    requestBody: UserProfileCreate;
};

export type ProfilesUpsertMyProfileResponse = (UserProfilePublic);

export type ProfilesDeleteMyProfileResponse = (unknown);

export type ProfilesUpdateMyProfileData = {
    requestBody: UserProfileUpdate;
};

export type ProfilesUpdateMyProfileResponse = (UserProfilePublic);

export type ProfilesGetMySavedRacesResponse = (RacesPublic);

export type ProfilesSaveRaceData = {
    raceId: string;
};

export type ProfilesSaveRaceResponse = (UserRaceInteractionPublic);

export type ProfilesUnsaveRaceData = {
    raceId: string;
};

export type ProfilesUnsaveRaceResponse = (unknown);

export type ProfilesTrackRaceViewData = {
    raceId: string;
};

export type ProfilesTrackRaceViewResponse = (UserRaceInteractionPublic);

export type ProvincesReadAdministrativeRegionsResponse = (Array<AdministrativeRegionPublic>);

export type ProvincesReadAdministrativeUnitsResponse = (Array<AdministrativeUnitPublic>);

export type ProvincesReadProvincesData = {
    limit?: number;
    skip?: number;
};

export type ProvincesReadProvincesResponse = (ProvincesPublic);

export type ProvincesReadProvinceData = {
    provinceCode: string;
};

export type ProvincesReadProvinceResponse = (ProvincePublicWithDetails);

export type ProvincesReadWardsByProvinceData = {
    limit?: number;
    provinceCode: string;
    skip?: number;
};

export type ProvincesReadWardsByProvinceResponse = (WardsPublic);

export type ProvincesReadWardData = {
    wardCode: string;
};

export type ProvincesReadWardResponse = (WardPublicWithDetails);

export type RaceAttributesReadRaceAttributesData = {
    isPublic?: (boolean | null);
    raceId: string;
};

export type RaceAttributesReadRaceAttributesResponse = (RaceAttributesPublic);

export type RaceAttributesCreateRaceAttributeData = {
    requestBody: RaceAttributeCreate;
};

export type RaceAttributesCreateRaceAttributeResponse = (RaceAttributePublic);

export type RaceAttributesReadRaceAttributeData = {
    attributeId: string;
};

export type RaceAttributesReadRaceAttributeResponse = (RaceAttributePublic);

export type RaceAttributesUpdateRaceAttributeData = {
    attributeId: string;
    requestBody: RaceAttributeUpdate;
};

export type RaceAttributesUpdateRaceAttributeResponse = (RaceAttributePublic);

export type RaceAttributesDeleteRaceAttributeData = {
    attributeId: string;
};

export type RaceAttributesDeleteRaceAttributeResponse = (Message);

export type RaceCategoriesReadRaceCategoriesData = {
    limit?: number;
    raceId: string;
    skip?: number;
};

export type RaceCategoriesReadRaceCategoriesResponse = (RaceCategoriesPublic);

export type RaceCategoriesCreateRaceCategoryData = {
    requestBody: RaceCategoryCreate;
};

export type RaceCategoriesCreateRaceCategoryResponse = (RaceCategoryPublic);

export type RaceCategoriesReadRaceCategoryData = {
    categoryId: string;
};

export type RaceCategoriesReadRaceCategoryResponse = (RaceCategoryPublicWithDetails);

export type RaceCategoriesUpdateRaceCategoryData = {
    categoryId: string;
    requestBody: RaceCategoryUpdate;
};

export type RaceCategoriesUpdateRaceCategoryResponse = (RaceCategoryPublic);

export type RaceCategoriesDeleteRaceCategoryData = {
    categoryId: string;
};

export type RaceCategoriesDeleteRaceCategoryResponse = (Message);

export type RaceCategoriesUpdateCategoryTranslationsData = {
    categoryId: string;
    requestBody: CategoryTranslationUpdate;
};

export type RaceCategoriesUpdateCategoryTranslationsResponse = (RaceCategoryPublic);

export type RaceCategoriesGetCategoryTranslationsData = {
    categoryId: string;
};

export type RaceCategoriesGetCategoryTranslationsResponse = ({
    [key: string]: unknown;
});

export type RaceRegistrationsReadRaceRegistrationsData = {
    categoryId?: (string | null);
    limit?: number;
    raceId?: (string | null);
    skip?: number;
};

export type RaceRegistrationsReadRaceRegistrationsResponse = (RaceRegistrationsPublic);

export type RaceRegistrationsCreateRaceRegistrationData = {
    requestBody: RaceRegistrationCreate;
};

export type RaceRegistrationsCreateRaceRegistrationResponse = (RaceRegistrationPublic);

export type RaceRegistrationsReadMyRegistrationsData = {
    limit?: number;
    skip?: number;
};

export type RaceRegistrationsReadMyRegistrationsResponse = (RaceRegistrationsPublic);

export type RaceRegistrationsReadRaceRegistrationData = {
    registrationId: string;
};

export type RaceRegistrationsReadRaceRegistrationResponse = (RaceRegistrationPublicWithDetails);

export type RaceRegistrationsUpdateRaceRegistrationData = {
    registrationId: string;
    requestBody: RaceRegistrationUpdate;
};

export type RaceRegistrationsUpdateRaceRegistrationResponse = (RaceRegistrationPublic);

export type RaceRegistrationsDeleteRaceRegistrationData = {
    registrationId: string;
};

export type RaceRegistrationsDeleteRaceRegistrationResponse = (Message);

export type RaceResultsReadRaceResultsData = {
    limit?: number;
    raceId: string;
    skip?: number;
};

export type RaceResultsReadRaceResultsResponse = (RaceResultsPublic);

export type RaceResultsCreateRaceResultData = {
    requestBody: RaceResultCreate;
};

export type RaceResultsCreateRaceResultResponse = (RaceResultPublic);

export type RaceResultsReadRaceResultData = {
    resultId: string;
};

export type RaceResultsReadRaceResultResponse = (RaceResultPublic);

export type RaceResultsUpdateRaceResultData = {
    requestBody: RaceResultUpdate;
    resultId: string;
};

export type RaceResultsUpdateRaceResultResponse = (RaceResultPublic);

export type RaceResultsDeleteRaceResultData = {
    resultId: string;
};

export type RaceResultsDeleteRaceResultResponse = (Message);

export type RaceResultsReadRaceResultByRegistrationData = {
    registrationId: string;
};

export type RaceResultsReadRaceResultByRegistrationResponse = (RaceResultPublic);

export type RacesSearchRacesData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    difficulty?: (DifficultyEnum | null);
    distanceMaxKm?: (number | null);
    distanceMinKm?: (number | null);
    lat?: (number | null);
    limit?: number;
    lon?: (number | null);
    /**
     * Filter by province code
     */
    provinceCode?: (string | null);
    /**
     * Full-text search query
     */
    q?: (string | null);
    radiusKm?: (number | null);
    skip?: number;
    sort?: string;
    status?: (RaceStatusEnum | null);
    tagSlugs?: (Array<(string)> | null);
    terrain?: (TerrainEnum | null);
    /**
     * Filter by ward code
     */
    wardCode?: (string | null);
};

export type RacesSearchRacesResponse = (RacesPublic);

export type RacesGetNearbyRacesData = {
    lat: number;
    limit?: number;
    lon: number;
    radiusKm?: number;
};

export type RacesGetNearbyRacesResponse = (RacesPublicWithDistance);

export type RacesGetTrendingRacesData = {
    days?: number;
    limit?: number;
};

export type RacesGetTrendingRacesResponse = (RacesPublic);

export type RacesGetRecommendedRacesData = {
    limit?: number;
};

export type RacesGetRecommendedRacesResponse = (RacesPublicWithExplanation);

export type RacesReadMyOrganizedRacesData = {
    limit?: number;
    skip?: number;
};

export type RacesReadMyOrganizedRacesResponse = (RacesPublic);

export type RacesReadRacesData = {
    limit?: number;
    organizerId?: (string | null);
    search?: (string | null);
    skip?: number;
    startDateFrom?: (string | null);
    startDateTo?: (string | null);
    status?: (string | null);
};

export type RacesReadRacesResponse = (RacesPublic);

export type RacesCreateRaceData = {
    requestBody: RaceCreate;
};

export type RacesCreateRaceResponse = (RacePublic);

export type RacesGenerateRaceDetailsData = {
    requestBody: RaceNameInput;
};

export type RacesGenerateRaceDetailsResponse = (AIRaceSuggestion);

export type RacesGenerateRaceImageEndpointData = {
    requestBody: ImageGenerationInput;
};

export type RacesGenerateRaceImageEndpointResponse = (unknown);

export type RacesReadRaceData = {
    raceId: string;
};

export type RacesReadRaceResponse = (RacePublicWithDetails);

export type RacesUpdateRaceData = {
    raceId: string;
    requestBody: RaceUpdate;
};

export type RacesUpdateRaceResponse = (RacePublic);

export type RacesDeleteRaceData = {
    raceId: string;
};

export type RacesDeleteRaceResponse = (Message);

export type RacesGetSimilarRacesData = {
    limit?: number;
    raceId: string;
};

export type RacesGetSimilarRacesResponse = (RacesPublic);

export type RacesAutoTagRaceData = {
    raceId: string;
};

export type RacesAutoTagRaceResponse = (TagSuggestion);

export type RacesEnhanceRaceDescriptionData = {
    raceId: string;
};

export type RacesEnhanceRaceDescriptionResponse = (DescriptionSuggestion);

export type RacesAskRaceQuestionData = {
    raceId: string;
    requestBody: AskRequest;
};

export type RacesAskRaceQuestionResponse = (RaceAnswer);

export type RacesUpdateRaceTranslationsData = {
    raceId: string;
    requestBody: RaceTranslationUpdate;
};

export type RacesUpdateRaceTranslationsResponse = (RacePublic);

export type RacesGetRaceTranslationsData = {
    raceId: string;
};

export type RacesGetRaceTranslationsResponse = ({
    [key: string]: unknown;
});

export type RolesReadRolesData = {
    limit?: number;
    skip?: number;
};

export type RolesReadRolesResponse = (RolesPublic);

export type RolesCreateRoleData = {
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (RolePublic);

export type RolesReadRoleData = {
    roleId: string;
};

export type RolesReadRoleResponse = (RolePublic);

export type RolesUpdateRoleData = {
    requestBody: RoleUpdate;
    roleId: string;
};

export type RolesUpdateRoleResponse = (RolePublic);

export type RolesDeleteRoleData = {
    roleId: string;
};

export type RolesDeleteRoleResponse = (Message);

export type RolesAssignRoleToUserData = {
    roleId: string;
    userId: string;
};

export type RolesAssignRoleToUserResponse = (UserPublic);

export type RolesRemoveRoleFromUserData = {
    roleId: string;
    userId: string;
};

export type RolesRemoveRoleFromUserResponse = (UserPublic);

export type TagsListTagsResponse = (TagsPublic);

export type TagsCreateTagData = {
    requestBody: RaceTagCreate;
};

export type TagsCreateTagResponse = (TagPublic);

export type TagsSetTagsForRaceData = {
    raceId: string;
    requestBody: Array<(string)>;
};

export type TagsSetTagsForRaceResponse = (Array<TagPublic>);

export type TagsUpdateTagTranslationsData = {
    requestBody: TagTranslationUpdate;
    tagId: string;
};

export type TagsUpdateTagTranslationsResponse = (TagPublic);

export type TagsGetTagTranslationsData = {
    tagId: string;
};

export type TagsGetTagTranslationsResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);