"""Add CMS module tables

Revision ID: 21cfb2e6b325
Revises: 0cf922026289
Create Date: 2026-06-06 12:02:45.073161

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21cfb2e6b325'
down_revision = '0cf922026289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogcategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blogcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogcategory_name'), 'blogcategory', ['name'], unique=True)
    op.create_index(op.f('ix_blogcategory_slug'), 'blogcategory', ['slug'], unique=True)
    op.create_table('blogtag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogtag_name'), 'blogtag', ['name'], unique=True)
    op.create_index(op.f('ix_blogtag_slug'), 'blogtag', ['slug'], unique=True)
    op.create_table('menu',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_name'), 'menu', ['name'], unique=True)
    op.create_index(op.f('ix_menu_slug'), 'menu', ['slug'], unique=True)
    op.create_table('blogpost',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('featured_image_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('featured_image_alt', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('meta_keywords', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('og_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('og_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('og_image_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('canonical_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_sticky', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('default_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('post_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['blogcategory.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogpost_slug'), 'blogpost', ['slug'], unique=True)
    op.create_index(op.f('ix_blogpost_title'), 'blogpost', ['title'], unique=False)
    op.create_table('mediafolder',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['mediafolder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediafolder_name'), 'mediafolder', ['name'], unique=False)
    op.create_table('menuitem',
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('css_classes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['menuitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('meta_keywords', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('og_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('og_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('og_image_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('canonical_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_homepage', sa.Boolean(), nullable=False),
    sa.Column('is_visible_in_menu', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('default_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('page_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_slug'), 'page', ['slug'], unique=True)
    op.create_index(op.f('ix_page_title'), 'page', ['title'], unique=False)
    op.create_table('blogtaglink',
    sa.Column('blog_post_id', sa.Uuid(), nullable=False),
    sa.Column('blog_tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blogpost.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blog_tag_id'], ['blogtag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_post_id', 'blog_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogtaglink')
    op.drop_index(op.f('ix_page_title'), table_name='page')
    op.drop_index(op.f('ix_page_slug'), table_name='page')
    op.drop_table('page')
    op.drop_table('menuitem')
    op.drop_index(op.f('ix_mediafolder_name'), table_name='mediafolder')
    op.drop_table('mediafolder')
    op.drop_index(op.f('ix_blogpost_title'), table_name='blogpost')
    op.drop_index(op.f('ix_blogpost_slug'), table_name='blogpost')
    op.drop_table('blogpost')
    op.drop_index(op.f('ix_menu_slug'), table_name='menu')
    op.drop_index(op.f('ix_menu_name'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_blogtag_slug'), table_name='blogtag')
    op.drop_index(op.f('ix_blogtag_name'), table_name='blogtag')
    op.drop_table('blogtag')
    op.drop_index(op.f('ix_blogcategory_slug'), table_name='blogcategory')
    op.drop_index(op.f('ix_blogcategory_name'), table_name='blogcategory')
    op.drop_table('blogcategory')
    # ### end Alembic commands ###
